### ISSUE TITLE
Add readme file in the project.

### ISSUE THREAD

**Issue by Sandigupta** [microsoftdotnetdevelopment/News-Portal#1]
The project currently lacks a README.md file, which is essential for providing an overview of the project, setup instructions, and other relevant details. A well-structured README helps developers and users understand the purpose of the project, how to install it, and how to contribute.

**Comment by sunny7899** [comment]
Great Go ahead @Sandigupta If possible attach screenshots of UIs also

**Comment by Sandigupta** [comment]
@sunny7899 
Hey! This issue is not assigned to me. Can you check it?

**Comment by Sandigupta** [comment]
Okay, I am working on it.
