### ISSUE TITLE
Project setup and run

### ISSUE THREAD

**Issue by sunny7899** [microsoftdotnetdevelopment/News-Portal#4]

**Comment by sunny7899** [comment]
@DidiNDexter Can you please work on it also in that PR. assign this issue to yourself

**Comment by DidiNDexter** [comment]
> @DidiNDexter Can you please work on it also in that PR. assign this issue to yourself

Yes sure , let me work on it now @sunny7899

**Comment by DidiNDexter** [comment]
This has been done. Please confirm that it is okay and accept @sunny7899
